#ifndef GUARD_DEFINE_GSC_H
#define GUARD_DEFINE_GSC_H

#define VERSION_GOLD 1
#define VERSION_SILVER 2
#define VERSION_CRYSTAL 3

#define LANGUAGE_CHINESE 8

#define NAME_LENGTH_GSC_JP 5
#define NAME_LENGTH_GSC_INTL 10

#define BOX_MON_TOTAL_GSC_JP 30
#define BOX_MON_TOTAL_GSC_INTL 20

#define BOX_TOTAL_GSC_JP 9
#define BOX_TOTAL_GSC_INTL 14

#endif